: 1+ 1 + ;
: 1- 1 - ;
: 2dup swap dup rot dup rot swap ;
: 2drop drop drop ;
: <> = 0= ;
: 0<> 0 <> ;
: > 2dup < 0= rot rot <> and ;
: 0> 0 > ;
: bl S"  " drop C@ ;
: c 1 allot ;
: cell+ 1 cells + ;
: char+ 1+ ;
: chars ;
: max 2dup < if swap then drop ;
: negate -1 * ;
: min 2dup max negate + + ;
: nip swap drop ;
: over 2dup drop ;
: tuck dup rot swap ;

